; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
extra_scripts =
    secrets_configure.py

board_build.filesystem = spiffs

build_flags =
    -DARDUINO_PARTITION_min_spiffs
    -DARDUINO_EVENT_RUNNING_CORE=1   ;0:Core0, 1:Core1(default)
    -DARDUINO_RUNNING_CORE=1         ;0:Core0, 1:Core1(default)
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -mfix-esp32-psram-cache-strategy=memw
    -D SSD1306_NO_SPLASH
    -D DEMOD_DEBUG
    -D RF_MODULE_INIT_STATUS
    -D REGOOKFIX_DEBUG
    -D setBitrate
;   -D MEMORY_DEBUG

;  TTGO LORA
;[env:ttgo-lora32-v21]
;monitor_filters = esp32_exception_decoder
;platform = espressif32
;board = ttgo-lora32-v21
;framework = arduino
;lib_deps =
;    adafruit/Adafruit GFX Library@^1.11.9
;    adafruit/Adafruit SSD1306@^2.5.9
;    thijse/ArduinoLog@^1.1.1
;    bblanchon/ArduinoJson@^7.0.3
;    zeed/AsyncTCP@^1.1.1
;    ottowinter/ESPAsyncWebServer-esphome@^3.1.0
;    rtl_433_ESP_acurite

;https://tanakamasayuki.github.io/M5Stack-PlatformIO/platformio.ini-Generator.html

[env:m5stack-core2]
monitor_filters = esp32_exception_decoder
platform = espressif32
board = m5stack-core2
framework = arduino
lib_deps =
    m5stack/M5Unified @ ^0.1.16  ; Ensure you use the latest version
    m5stack/M5GFX @ ^0.1.16     ; Recommended for display support
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit SSD1306@^2.5.9
    thijse/ArduinoLog@^1.1.1
    bblanchon/ArduinoJson@^7.0.3
    zeed/AsyncTCP@^1.1.1
    ottowinter/ESPAsyncWebServer-esphome@^3.1.0
    rtl_433_ESP_acurite

build_flags =
   '-DRF_SX1276="SX1276"'   ; M5 core2 
   '-DRF_MODULE_DIO0=-1'    ; SX1276 pin DIO0
   '-DRF_MODULE_DIO1=-1'    ; SX1276 pin DIO1
   '-DRF_MODULE_DIO2=35'    ; SX1276 pin DIO2     ;   m5stack/M5Stack @ ^0.3.6
    -DCORE_DEBUG_LEVEL=0             ;0:None, 1:Error, 2:Warn, 3:Info, 4:Debug, 5:Verbose
    -Dyyyyyyyyyyyyyyyyyyyyyyyyyy_core2


board_build.mcu = esp32
board_build.f_cpu = 240000000L

monitor_speed = 115200
;---------------------------------------------------------

;;;[env:m5stack-cores3]
;;;;platform = espressif32@6.7.0
;;;platform = espressif32
;;;board = m5stack-cores3
;;;framework = arduino
;;;upload_speed = 1500000

;;;; https://community.platformio.org/t/board-build-partitions-which-option-is-the-right-one/37201
;;;; see file:// espressif/arduino-esp32/blob/2.0.11/tools/partitions/min_spiffs.csv
;;;board_build.partitions = min_spiffs.csv
;;;
;;;build_flags =
;;;    -DESP32S3
;;;    -Dxxxxxxxxxxxxxxxxxxxxxxxxxx_core_s3
;;;    -DCORE_DEBUG_LEVEL=3             ;0:None, 1:Error, 2:Warn, 3:Info, 4:Debug, 5:Verbose
;;;    -DARDUINO_USB_CDC_ON_BOOT=1 
;;;    -DARDUINO_USB_MSC_ON_BOOT=0 
;;;    -DARDUINO_USB_DFU_ON_BOOT=0
;;;    -DARDUINO_M5STACK_CORES3
;;;
;;;    
;;;lib_deps =
;;;;;; m5stack/M5CoreS3
;;;    m5stack/M5Unified ;				@ ^0.1.16  ; Ensure you use the latest version
;;;    m5stack/M5GFX ;					@ ^0.1.16  ; Recommended for display support
;;;    adafruit/Adafruit GFX Library@^1.11.9
;;;    adafruit/Adafruit SSD1306@^2.5.9
;;;    thijse/ArduinoLog@^1.1.1
;;;    bblanchon/ArduinoJson@^7.0.3
;;;    zeed/AsyncTCP@^1.1.1
;;;    ottowinter/ESPAsyncWebServer-esphome@^3.1.0
;;;    rtl_433_ESP_acurite
;;;;   m5stack/M5Stack @ ^0.3.6
;;;;   M5Unified=https://github.com/m5stack/M5Unified
